services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d/

  app:
    build: .
    ports:
      - "8080:8080"

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-6.2-latest
    # ports:
    #   - "10051:10051"
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
    depends_on:
      - postgres

  zabbix-web-apache-pgsql:
    image: zabbix/zabbix-web-apache-pgsql:alpine-6.2-latest
    # ports:
    #   - "8081:8081"
    #   - "8443:8443"
    environment:
      DB_SERVER_HOST: postgres
    depends_on:
      - postgres
      - zabbix-server

  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-6.2-latest
    # ports:
    #   - "10050:10050"
